version: "3"

volumes:
  etebase_data:

services:
  etebase:
    image: victorrds/etesync:alpine
    container_name: "etebase"
    volumes:
      - etebase_data:/data:rw
    environment:
      SERVER: http-socket
      SUPER_USER: admin
      SUPER_PASS: Change_M3
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.services.etebase.loadbalancer.server.port: "3735"
      traefik.http.services.etebase.loadbalancer.server.scheme: "http"
      traefik.http.routers.etebase.rule: "Host(`etebase.localhost`)"
      traefik.http.routers.etebase.entrypoints: "web"
      traefik.http.routers.etebase.service: "etebase"

  traefik:
    image: "traefik:2.3"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always