---
name: Test Pull Request on the Alpine Image

on:
  pull_request:
    branches:
      - master
      - dev
    paths:
      - "context/**"
      - "tags/alpine/Dockerfile"
      - ".github/workflows/pr_alpine.yml"

jobs:
  pr-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dockerfiles and Context
        uses: actions/checkout@v2

      - name: Checkout Etebase Server source
        uses: actions/checkout@v2
        with:
          repository: etesync/server
          path: server

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.0.2

      - name: Alpine PR Build
        id: docker_pr_build
        uses: docker/build-push-action@v2.1.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./tags/alpine/Dockerfile
          push: false
          tags: victorrds/etebase:${{ github.sha }}-alpine