name: Build and Push Alpine Tags

on:
  push:
    branches: [ legacy ]
    paths:
      - 'context/**'
      - 'tags/alpine/Dockerfile'
      - '.github/workflows/release-alpine.yml'
jobs:  
  build-legacy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'legacy'
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: victorrds/etesync
        always_pull: true
        add_git_labels: true
        push: true
        dockerfile: ./tags/alpine/Dockerfile
        tags: legacy-alpine,0.3.0-alpine
        build_args: TAG=v0.3.0