name: Build and Push

on:
  push:
    branches: [ release ]

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: victorrds/etesync
        always_pull: true
        add_git_labels: true
        push: true
        path: ./tags/base/Dockerfile
        tags: latest
        build_args: TAG=master

  build-slim:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: victorrds/etesync
        always_pull: true
        add_git_labels: true
        push: true
        path: ./tags/slim/Dockerfile
        tags: slim
        build_args: TAG=master
  
  build-alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: victorrds/etesync
        always_pull: true
        add_git_labels: true
        push: true
        path: ./tags/alpine/Dockerfile
        tags: alpine
        build_args: TAG=master