name: 'Get Labels'
description: 'Preapare common image labels'
inputs:
  authors:  # id of input
    description: 'Authors'
    required: true
  title:
    description: 'Image title'
    required: true
  version:
    description: 'The image version'
    required: true
outputs:
  labels: 
    description: "Labels List"
    value: ${{ steps.get_labels.outputs.labels }}
runs:
  using: "composite"
  steps: 
    - id: get_labels
      shell: bash
      run: |
        LABELS="org.opencontainers.image.title='${{ inputs.title }}'
        org.opencontainers.image.version=${{ inputs.version }}
        org.opencontainers.image.authors='${{ inputs.authors }}'
        org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        org.opencontainers.image.source=${{ github.event.repository.html_url }}
        org.opencontainers.image.revision=${{ github.sha }}"
        LABELS="${LABELS//'%'/'%25'}"
        LABELS="${LABELS//$'\n'/'%0A'}"
        LABELS="${LABELS//$'\r'/'%0D'}"
        echo "::set-output name=labels::${LABELS}"
